---
title: "Anaylze "
author: "H Qin"
date: "11/1 - 11/9 /2017 "
output: html_document
---
See 
http://hongqinlab.blogspot.com/2017/11/cellmap-gin-output.html
http://hongqinlab.blogspot.com/2017/06/yeast-genetic-map.html

```{r}
rm(list=ls());
set.seed(2017);
datapath = "~/github/cellmap_parent/cellmap_data/";
#datapath = "~/github/cellmap_parent/CellMap/20170626/S1.pairwise/"; #ridgeside
#datapath = "~/data/Sce/CellMap/20170626/S1.pairwise/"; #applejack
debug = 0;
list.files(path=datapath);
```

Load unique pairwise genetic interaction data, generated by cellmap_analysis/cellmap_explore20171101ridgeside.Rmd
```{r}
tb.gin.intermediate = read.csv( paste(datapath, "gin_intermediate_uniquePairs20171115.csv", sep=''));

tb.gin.stringenet = read.csv( paste(datapath, "gin_stringent_uniquePairs20171115.csv", sep=''));
tb.gin.stringenet$essenflag1 = as.character(tb.gin.stringenet$essenflag1)
tb.gin.stringenet$essenflag2 = as.character(tb.gin.stringenet$essenflag2)

```

How many interactions per gene? Hundreds for intermediate GIN. 
```{r}
tb = tb.gin.intermediate;
longname = c( as.character(tb$ORF1), as.character(tb$ORF2) );
net = table( longname);
str(net)
mean(net)
median(net)
```

Stringent GIN
```{r}
tb = tb.gin.stringenet;
longname = c( as.character(tb$ORF1), as.character(tb$ORF2) );
net = table( longname);
str(net)
mean(net)
median(net)
```

For Hong's reliability aging model, we need to find out the interactions per essential gene.

```{r}
tb = tb.gin.stringenet;
tb$essenflag1[ is.na(tb$essenflag1)  ] = 'missing'; 
tb$essenflag2[ is.na(tb$essenflag2)  ] = 'missing'; 
table(tb$essenflag1)
table(tb$essenflag2);

tb$AgingFlag = 'Nonaging-intxn'
tb$AgingFlag = ifelse( tb$essenflag1=='essential' | tb$essenflag2 =='essential', 'Aging-intxn', tb$AgingFlag );
table(tb$AgingFlag) 
table(tb$AgingFlag) /length(tb$AgingFlag)

tb2 = tb[tb$AgingFlag=='Aging-intxn', ]
net2 = table( c( as.character(tb2$ORF1), as.character(tb2$ORF2)) ); 
mean(net2)
median(net2)

#how about positive gin?
tb2postive = tb2[ tb2$Genetic.interaction.score..ε. > 0, ]
net2positive = table( c( as.character(tb2postive$ORF1), as.character(tb2postive$ORF2)) ); 
mean(net2positive )
median(net2positive )

#how about negative gin? 
tb2negative = tb2[ tb2$Genetic.interaction.score..ε. < 0, ]
net2negative = table( c( as.character(tb2negative$ORF1), as.character(tb2negative$ORF2)) ); 
mean(net2negative )
median(net2negative )


```

